name: Build

on:
  push:
    tags: 
    - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ReleaseFileName: SimHubToF12020UDP_${{ github.ref_name }}.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild /p:Configuration=Release

    - name: Zip output DLL file
      run: Compress-Archive -Path ./SimHubToF12020UDP/bin/Release/SimHubToF12020UDP.dll -DestinationPath ./${{ env.ReleaseFileName }}
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: ${{ env.ReleaseFileName }}
