name: Build

on:
  push:
    branches: [main]
    paths: ["SimHubSF1000UDP/**", "SimHubSF1000UDP.sln", "libs/**"]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build plugin DLL file
      run: msbuild /p:Configuration=Release
