name: SimHub Update & Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-slim

    outputs:
      should_run: ${{ steps.precheck.outputs.should_run }}
      latest_tag: ${{ steps.precheck.outputs.latest_tag }}
      current_tag: ${{ steps.precheck.outputs.current_tag }}
      download_url: ${{ steps.precheck.outputs.download_url }}

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest binary
        id: precheck
        continue-on-error: true
        run: |
          curl -Ls "https://api.github.com/repos/SHWotever/SimHub/releases/latest" -o latest_simhub.json
          LATEST_TAG=$(grep -Po '"tag_name": "\K[^"]*' ./latest_simhub.json)
          DOWNLOAD_URL=$(grep -Po '"browser_download_url": "\K[^"]*' ./latest_simhub.json)
          CURRENT_TAG=$(<./libs/SimHub/VERSION)

          echo "Latest build: $LATEST_TAG"
          echo "Last built: $CURRENT_TAG"
          echo "Download link: $DOWNLOAD_URL"

          if [ "$LATEST_TAG" != "$CURRENT_TAG" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
            echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
            echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
            echo "New version found"
            exit 0
          fi

          echo "should_run=false" >> $GITHUB_OUTPUT
          exit 0

  update-simhub:
    runs-on: windows-latest

    needs:
      - check-update

    if: ${{ needs.check-update.outputs.should_run == 'true' }}

    outputs:
      new_version: ${{ steps.version.outputs.new_version }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Download and install SimHub
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ needs.check-update.outputs.download_url }}" -OutFile "C:\SimHub.zip"
          Expand-Archive -Path "C:\SimHub.zip" -DestinationPath "C:\" -Force

          New-Item -Path "C:\" -Name "simhub" -ItemType "Directory"
          C:\SimHubSetup_${{ needs.check-update.outputs.latest_tag }}.exe /VERYSILENT /Dir="C:\simhub"

          do {
            Write-Output "Waiting for files..."
            Start-Sleep -Seconds 5
          } until (
            (Test-Path -path "C:\simhub\GameReaderCommon.dll" -PathType Leaf) -and
            (Test-Path -path "C:\simhub\SimHub.Logging.dll" -PathType Leaf) -and
            (Test-Path -path "C:\simhub\SimHub.Plugins.dll" -PathType Leaf) -and
            (Test-Path -path "C:\simhub\log4net.dll" -PathType Leaf)
          )

          Start-Sleep -Seconds 3
          Write-Output "All files are found"

      - name: Update libs
        run: |
          Copy-Item "C:\simhub\GameReaderCommon.dll" -Destination "./libs/SimHub/" -Force
          Copy-Item "C:\simhub\SimHub.Logging.dll" -Destination "./libs/SimHub/" -Force
          Copy-Item "C:\simhub\SimHub.Plugins.dll" -Destination "./libs/SimHub/" -Force
          Copy-Item "C:\simhub\log4net.dll" -Destination "./libs/SimHub/" -Force
          "${{ needs.check-update.outputs.latest_tag }}" | Set-Content "./libs/SimHub/VERSION"

      - name: Bump version
        id: version
        shell: pwsh
        run: |
          git fetch --tags --force
          $tags = git tag --sort=-v:refname | Where-Object { $_ -match '^v\d+\.\d+\.\d+$' }
          if (-not $tags -or $tags.Count -eq 0) {
            Write-Error "No tags found. Cannot determine current version."
            exit 1
          } else {
            $latest = $tags | Select-Object -First 1
            $version = $latest.Substring(1)
            $parts = $version.Split('.')
            $parts[2] = [int]$parts[2] + 1
            $newVersion = "v" + ($parts -join '.')
          }
          Write-Output "New version: $newVersion"
          "new_version=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps-dev): Bump SimHub from v${{ needs.check-update.outputs.current_tag }} to v${{ needs.check-update.outputs.latest_tag }}"
          git tag ${{ steps.version.outputs.new_version }}
          git push origin main --tags

  build:
    runs-on: windows-latest

    needs:
      - update-simhub

    env:
      ReleaseFileName: SimHubSF1000UDP_${{ needs.update-simhub.outputs.new_version }}.zip

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build plugin DLL file
        run: msbuild /p:Configuration=Release

      - name: Zip output DLL file
        run: Compress-Archive -Path ./SimHubSF1000UDP/bin/Release/SimHubSF1000UDP.dll -DestinationPath ./${{ env.ReleaseFileName }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-file
          path: ${{ env.ReleaseFileName }}

  generate-changelog:
    runs-on: ubuntu-slim

    needs:
      - update-simhub

    permissions:
      contents: read

    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv -l -s all
        env:
          OUTPUT: CHANGES.md

  release:
    runs-on: ubuntu-slim

    needs:
      - update-simhub
      - build
      - generate-changelog

    permissions:
      contents: write

    env:
      ReleaseFileName: SimHubSF1000UDP_${{ needs.update-simhub.outputs.new_version }}.zip

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: build-file

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.update-simhub.outputs.new_version }}
          name: ${{ needs.update-simhub.outputs.new_version }}
          body: "${{ needs.generate-changelog.outputs.release_body }}"
          fail_on_unmatched_files: true
          files: ${{ env.ReleaseFileName }}
